sudo: false

language: scala

scala:
  - 2.11.8
  - 2.10.6

jdk:
  - oraclejdk7

matrix:
  include:
  - scala: 2.12.0
    jdk: oraclejdk8

script: ./sbt ++$TRAVIS_SCALA_VERSION clean coreJS/test lawsJS/test && ./sbt ++$TRAVIS_SCALA_VERSION clean coverage coreJVM/test lawsJVM/test coverageReport # mimaReportBinaryIssues

after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  irc:
    channels:
      - "chat.freenode.net#spire-math"
    on_success: change
    on_failure: always
